//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CO5027
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookImage
    {
        public int BookImageID { get; set; }
        public string BookImageAlternateText { get; set; }
        public int BookImageWidth { get; set; }
        public int BookImageHeight { get; set; }
        public string BookImageExtension { get; set; }
    }
}
