//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CO5027
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookDetail
    {
        public int BookID { get; set; }
        public string BookName { get; set; }
        public string BookCategory { get; set; }
        public string BookGenre { get; set; }
        public string BookPrice { get; set; }
        public string BookLanguage { get; set; }
        public string BookAuthor { get; set; }
        public string BookPublish { get; set; }
        public string BookPages { get; set; }
        public string BookDescription { get; set; }
    }
}
