//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CO5027
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Table
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductDetail { get; set; }
        public Nullable<double> ProductPrice { get; set; }
        public Nullable<int> ProductQuantity { get; set; }
    }
}
